/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as token from "./token";
export type { token };
export type { DPMarketplaceC1 } from "./DPMarketplaceC1";
