/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockErc20Sol from "./MockERC20.sol";
export type { mockErc20Sol };
import type * as nftMinterImplementedSol from "./NFTMinterImplemented.sol";
export type { nftMinterImplementedSol };
export type { NFT } from "./NFT";
export type { NFT1155 } from "./NFT1155";
